
#ifndef DATA_H
#include <stdbool.h>

#define SYMBS \
X(NT_PROGRAM)\
X(NT_IDENTIFIER_LIST)\
X(NT_DECLARATIONS)\
X(NT_TYPE)\
X(NT_STANDARD_TYPE)\
X(NT_SUBPROGRAM_DECLARATIONS)\
X(NT_SUBPROGRAM_DECLARATION)\
X(NT_SUBPROGRAM_HEAD)\
X(NT_ARGUMENTS)\
X(NT_PARAMETER_LIST)\
X(NT_COMPOUND_STATEMENT)\
X(NT_OPTIONAL_STATEMENTS)\
X(NT_STATEMENT_LIST)\
X(NT_STATEMENT)\
X(NT_VARIABLE)\
X(NT_PROCEDURE_STATEMENT)\
X(NT_EXPRESSION_LIST)\
X(NT_EXPRESSION)\
X(NT_SIMPLE_EXPRESSION)\
X(NT_TERM)\
X(NT_FACTOR)\
X(NT_SIGN)\
X(NT_IDENTIFIER_LIST_)\
X(NT_DECLARATIONS_)\
X(NT_SUBPROGRAM_DECLARATIONS_)\
X(NT_PARAMETER_LIST_)\
X(NT_STATEMENT_LIST_)\
X(NT_EXPRESSION_LIST_)\
X(NT_SIMPLE_EXPRESSION_)\
X(NT_TERM_)\
X(NT_PROGRAM_)\
X(NT_PROGRAM__)\
X(NT_SUBPROGRAM_DECLARATION_)\
X(NT_SUBPROGRAM_DECLARATION__)\
X(NT_SUBPROGRAM_HEAD_)\
X(NT_COMPOUND_STATEMENT_)\
X(NT_STATEMENT_)\
X(NT_VARIABLE_)\
X(NT_PROCEDURE_STATEMENT_)\
X(NT_EXPRESSION_)\
X(NT_FACTOR_)\
X(T_PROGRAM)\
X(T_ID)\
X(T_VAR)\
X(T_ARRAY)\
X(T_NUM)\
X(T_OF)\
X(T_INTEGER)\
X(T_REAL)\
X(T_PROCEDURE)\
X(T_BEGIN)\
X(T_END)\
X(T_ASSIGNOP)\
X(T_IF)\
X(T_THEN)\
X(T_ELSE)\
X(T_WHILE)\
X(T_DO)\
X(T_CALL)\
X(T_RELOP)\
X(T_ADDOP)\
X(T_MULOP)\
X(T_NOT)\
X(T_LPAREN)\
X(T_RPAREN)\
X(T_SEMICOLON)\
X(T_PERIOD)\
X(T_COMMA)\
X(T_COLON)\
X(T_LBRACE)\
X(T_RBRACE)\
X(T_PLUS)\
X(T_MINUS)\
X(T_DOUBLEPERIOD)\
X(T_EOF)

typedef int Symbol;
typedef int Terminal;
typedef int NonTerminal;

Terminal nextTerminal(void);
bool isTerminal(Symbol s);
bool isNonTerminal(Symbol s);

#define DATA_H
#endif
