#ifndef PARSER_H
#define PARSER_H

#include "types.h"
#include "machines.h"

typedef MachineResult Terminal;

#define NONTERMS \
X(NT_ARGUMENTS) \
X(NT_COMPOUND_STATEMENT) \
X(NT_COMPOUND_STATEMENT1) \
X(NT_DECLARATIONS) \
X(NT_DECLARATIONS_) \
X(NT_EXPRESSION) \
X(NT_EXPRESSION1) \
X(NT_EXPRESSION_LIST) \
X(NT_EXPRESSION_LIST_) \
X(NT_FACTOR) \
X(NT_FACTOR1) \
X(NT_IDENTIFIER_LIST) \
X(NT_IDENTIFIER_LIST_) \
X(NT_OPTIONAL_STATEMENTS) \
X(NT_PARAMETER_LIST) \
X(NT_PARAMETER_LIST_) \
X(NT_PROCEDURE_STATEMENT) \
X(NT_PROCEDURE_STATEMENT1) \
X(NT_PROGRAM) \
X(NT_PROGRAM1) \
X(NT_PROGRAM11) \
X(NT_SIGN) \
X(NT_SIMPLE_EXPRESSION) \
X(NT_SIMPLE_EXPRESSION_) \
X(NT_STANDARD_TYPE) \
X(NT_STATEMENT) \
X(NT_STATEMENT1) \
X(NT_STATEMENT_LIST) \
X(NT_STATEMENT_LIST_) \
X(NT_SUBPROGRAM_DECLARATION) \
X(NT_SUBPROGRAM_DECLARATION1) \
X(NT_SUBPROGRAM_DECLARATION11) \
X(NT_SUBPROGRAM_DECLARATIONS) \
X(NT_SUBPROGRAM_DECLARATIONS_) \
X(NT_SUBPROGRAM_HEAD) \
X(NT_SUBPROGRAM_HEAD1) \
X(NT_TERM) \
X(NT_TERM_) \
X(NT_TYPE) \
X(NT_VARIABLE) \
X(NT_VARIABLE1)

#define X(a) a, 
typedef enum {
	NONTERMS
} NonTerminal;
#undef X

char *ntToString(NonTerminal);

#endif
